version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mel
      MYSQL_DATABASE: melDB
      MYSQL_USER: mel
      MYSQL_PASSWORD: mel
    volumes:
      - mysql_db:/var/lib/mysql

  app:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mel
      WORDPRESS_DB_PASSWORD: mel
      WORDPRESS_DB_NAME: melDB

volumes:
  mysql_db:
